version: '3.8'

services:
  cms-watcher:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-change-in-production
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - ./cache:/app/cache
      - ./watch_state:/app/watch_state
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for session storage and rate limiting
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - cms-watcher
    restart: unless-stopped
    profiles:
      - production

volumes:
  redis_data:

networks:
  default:
    driver: bridge 